### ISSUE TITLE
Refactoring: Refatorar todo o modal de adicionar grupo para que se adeque ao padrão dos outros modais existentes.

### ISSUE THREAD

**Issue by YtaloGabriel** [cerberus-project/cerberus-front#39]
- [x] O modal deve ter a estilização padrão de modais.
- [x] O modal deve ter validações de campos obrigatórios.
- [x] Caso o modal tente ser fechado com informações dentro de inputs, o sistema deve exibir o modal de alerta perguntando se o usuário tem certeza da ação.
